version: '3'
networks:
  tetris-network:
services:

  lb:
    image: 'dockercloud/haproxy:latest'
    container_name: haproxy
    links:
      - flex-config
      - flex-gateway
      - flex-service
      - flex-ui
    ports:
      - '80:80'
    networks:
      - tetris-network

  flex-config:
    image: consensus/flex-config:1.0.0-SNAPSHOT
    container_name: flex-config
    environment:
      - VIRTUAL_HOST=*/flex-config/*,https://*/flex-config/*
      - VIRTUAL_HOST_WEIGHT=3
    ports:
      - "8888:8888" # hostport:containerport
      - "8001:8000" # debugging port
    networks:
      - tetris-network

  flex-gateway:
    image: consensus/flex-gateway:1.0.0-SNAPSHOT
    container_name: flex-gateway
    environment:
      - VIRTUAL_HOST=*/flex-gateway/*,https://*/flex-gateway/*
      - VIRTUAL_HOST_WEIGHT=3
    ports:
      - "11552:11552" # hostport:containerport
      - "8002:8000" # debugging port
    networks:
      - tetris-network

  flex-service:
    image: consensus/flex-service:1.0.0-SNAPSHOT
    container_name: flex-service
    environment:
      - VIRTUAL_HOST=*/flex-service/*,https://*/flex-service/*
      - VIRTUAL_HOST_WEIGHT=3
    ports:
      - "11553:11553" # hostport:containerport
      - "8003:8000" # debugging port
    networks:
      - tetris-network

  flex-ui:
    image: consensus/flex-ui:1.0.0-SNAPSHOT
    container_name: flex-ui
    environment:
      - VIRTUAL_HOST=*/flex-ui/*,https://*/flex-ui/*
      - VIRTUAL_HOST_WEIGHT=3
    ports:
      - "11554:80" # hostport:containerport
      - "8004:8000"  # debugging port
    volumes:
      - ${WORKDIR}/Tetris/flex-ui/app:/usr/local/apache2/htdocs/app:cached
    networks:
      - tetris-network

  monitor:
    image: prom/prometheus
    container_name: monitor
    ports:
      - "9090:9090"
    networks:
      - tetris-network
